export const format = (data) => JSON.stringify(data)
.replaceAll(':"', "='").replaceAll('"=', " = ")
.replaceAll('","', "' , ")
.replaceAll('{"', "").replaceAll('"}', "'")
.replaceAll('":', " = ").replaceAll(',"', " , ")